"""initial migration

Revision ID: f997b811513f
Revises: 
Create Date: 2025-04-05 18:38:24.336967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f997b811513f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index('ix_enterprise-survey_index', table_name='enterprise-survey')
    op.drop_table('enterprise-survey')
    op.drop_index('ix_enterprise-table_index', table_name='enterprise-table')
    op.drop_table('enterprise-table')
    op.drop_index('ix_enterprise-retails_index', table_name='enterprise-retails')
    op.drop_table('enterprise-retails')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise-retails',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Year', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Industry_aggregation_NZSIOC', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Industry_code_NZSIOC', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Industry_name_NZSIOC', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Units', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Variable_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Variable_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Variable_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Industry_code_ANZSIC06', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_enterprise-retails_index', 'enterprise-retails', ['index'], unique=False)
    op.create_table('enterprise-table',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Year', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Industry_aggregation_NZSIOC', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Industry_code_NZSIOC', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Industry_name_NZSIOC', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Units', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Variable_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Variable_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Variable_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Industry_code_ANZSIC06', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_enterprise-table_index', 'enterprise-table', ['index'], unique=False)
    op.create_table('enterprise-survey',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Year', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Industry_aggregation_NZSIOC', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Industry_code_NZSIOC', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Industry_name_NZSIOC', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Units', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Variable_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Variable_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Variable_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Industry_code_ANZSIC06', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_enterprise-survey_index', 'enterprise-survey', ['index'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
